name: "Set Issue Label"
on:
  issues:
    types: [opened]

jobs:
  label_issue:
    name: Label Issue
    runs-on: ubuntu-latest
    steps:
      - name: bug
        uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["issue", "bug", "error"]'
          labels: '["bug"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: enhancement
        uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["enhancement", "feature", "add support"]'
          labels: '["enhancement"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: documentation
        uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["document"]'
          labels: '["documentation"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
